// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gadhittana-01/form-go/app"
	"github.com/gadhittana-01/form-go/db/repository"
	"github.com/gadhittana-01/form-go/handler"
	"github.com/gadhittana-01/form-go/service"
	"github.com/gadhittana-01/form-go/utils"
	"github.com/go-chi/chi"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeApp(route *chi.Mux, DB utils.PGXPool, config *utils.BaseConfig) (app.App, error) {
	repository := querier.NewRepository(DB)
	userSvc := service.NewUserSvc(repository, config)
	userHandler := handler.NewUserHandler(userSvc)
	appApp := app.NewApp(route, config, userHandler)
	return appApp, nil
}

// injector.go:

var userHandlerSet = wire.NewSet(querier.NewRepository, handler.NewUserHandler, service.NewUserSvc)
