// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package querier

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users"(name, identity_number, email, date_of_birth) VALUES
($1, $2, $3, $4) RETURNING id, name, identity_number, email, date_of_birth, created_at, updated_at
`

type CreateUserParams struct {
	Name           string    `json:"name"`
	IdentityNumber string    `json:"identity_number"`
	Email          string    `json:"email"`
	DateOfBirth    time.Time `json:"date_of_birth"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.IdentityNumber,
		arg.Email,
		arg.DateOfBirth,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdentityNumber,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
